"""
Popula o banco com cidades e notícias de exemplo, para você rodar o
projeto localmente sem depender dos feeds reais das prefeituras.

Uso:
    python -m scripts.seed_demo_data
"""
from datetime import datetime, timedelta

from app.database import Base, SessionLocal, engine
from app.models import City, News, FeedType

CITIES = [
    ("GAROPABA",FeedType.IPM,"https://garopaba.atende.net/cidadao/rss/noticias","governodegaropaba",1),
    ("PAULO LOPES",FeedType.FECAM,"https://paulolopes.sc.gov.br/noticias/","prefeiturapaulolopes",0),
    ("IMARUÍ",FeedType.FECAM,"https://imarui.sc.gov.br/noticias/","prefeituradeimarui",0),
    ("GRAVATAL",FeedType.IPM,"https://gravatal.atende.net/cidadao/rss/noticias","municipiodegravatal",1),
    ("IMBITUBA",FeedType.IPM,"https://imbituba.atende.net/cidadao/rss/noticias","prefeituradeimbituba",1),
    ("LAGUNA",FeedType.FECAM,"https://www.laguna.sc.gov.br/noticias/","prefeituradelaguna",0),
    ("PESCARIA BRAVA",FeedType.FECAM,"https://www.pescariabrava.sc.gov.br/noticias/","prefeiturapescariabrava",0),
    ("CAPIVARI DE BAIXO",FeedType.FECAM,"https://capivaridebaixo.sc.gov.br/noticias/","prefeituradecapivaridebaixo",0),
    ("ARARANGUÁ",FeedType.FECAM,"https://ararangua.sc.gov.br/noticias/","prefeituraararangua",0),
    ("ARMAZEM",FeedType.FECAM,"https://armazem.sc.gov.br/noticias/","prefeituraarmazem.sc",0),
    ("BALNEÁRIO ARROIO DO SILVA",FeedType.FECAM,"https://arroiodosilva.sc.gov.br/noticias/","prefeituradoarroio",0),
    ("BALNEÁRIO GAIVOTA",FeedType.PROPRIO,"https://www.balneariogaivota.sc.gov.br/noticias/","",0),
    ("BALNEÁRIO RINCÃO",FeedType.FECAM,"https://www.balneariorincao.sc.gov.br/noticias/","prefeiturarincao",0),
    ("BRAÇO DO NORTE",FeedType.FECAM,"https://bracodonorte.sc.gov.br/noticias/","prefsbn",0),
    ("COCAL DO SUL",FeedType.FECAM,"https://cocaldosul.sc.gov.br/noticias/","prefeituracocaldosul",0),
    ("CRICIÚMA",FeedType.PROPRIO,"https://www.criciuma.sc.gov.br/site/noticiaTodos.php#conteudo","",0),
    ("ERMO",FeedType.FECAM,"https://ermo.sc.gov.br/noticias/","prefeituradeermo",0),
    ("FORQUILHINHA",FeedType.FECAM,"https://www.forquilhinha.sc.gov.br/noticias/","governodeforquilhinha",0),
    ("GRÃO PARÁ",FeedType.FECAM,"https://www.graopara.sc.gov.br/noticias/","prefeituradegraopara",0),
    ("IÇARA",FeedType.PROPRIO,"https://www.icara.sc.gov.br/noticias/noticias","",0),
    ("JACINTO MACHADO",FeedType.IPM,"https://jacintomachado.atende.net/cidadao/rss/noticias","prefeiturajacintomachado",1),
    ("JAGUARUNA",FeedType.FECAM,"https://jaguaruna.sc.gov.br/noticias/","prefeituradejaguaruna",0),
    ("LAURO MULLER",FeedType.FECAM,"","",0),
    ("MARACAJÁ",FeedType.FECAM,"https://maracaja.sc.gov.br/noticias/","prefeiturademaracaja",0),
    ("MELEIRO",FeedType.FECAM,"https://meleiro.sc.gov.br/noticias/","meleiroemdestaque",0),
    ("MORRO DA FUMAÇA",FeedType.IPM,"https://morrodafumaca.atende.net/cidadao/rss/noticias","morrodafumaca",1),
    ("MORRO GRANDE",FeedType.FECAM,"https://morrogrande.sc.gov.br/noticias/","pref.morrogrande",0),
    ("NOVA VENEZA",FeedType.FECAM,"https://www.novaveneza.sc.gov.br/noticias/","prefeituranovaveneza",0),
    ("ORLEANS",FeedType.PROPRIO,"https://www.pmo.sc.gov.br/midia/noticias","",0),
    ("PASSO DE TORRES",FeedType.FECAM,"https://passodetorres.sc.gov.br/noticias/","prefeiturapassodetorres",0),
    ("PEDRAS GRANDES",FeedType.FECAM,"https://pedrasgrandes.sc.gov.br/noticias/","",0),
    ("PRAIA GRANDE",FeedType.IPM,"https://praiagrande.atende.net/cidadao/rss/noticias","prefeiturapraiagrandesc",1),
    ("RIO FORTUNA",FeedType.FECAM,"https://riofortuna.sc.gov.br/noticias/","prefeituraderiofortuna",0),
    ("SANGÃO",FeedType.FECAM,"https://sangao.sc.gov.br/noticias/","prefeiturasangao",0),
    ("SANTA ROSA DE LIMA",FeedType.IPM,"https://santarosadelima.atende.net/cidadao/rss/noticias","prefeiturasrl",1),
    ("SANTA ROSA DO SUL",FeedType.IPM,"https://santarosadosul.atende.net/cidadao/rss/noticias","prefeiturasantarosadosul",1),
    ("SÃO JOÃO DO SUL",FeedType.IPM,"https://saojoaodosul.atende.net/cidadao/rss/noticias","prefeituradesjs",1),
    ("SÃO LUDGERO",FeedType.PROPRIO,"https://www.saoludgero.sc.gov.br/noticias","municipiodesaoludgero",0),
    ("SÃO MARTINHO",FeedType.FECAM,"https://saomartinho.sc.gov.br/noticias/","prefeiturasaomartinho",0),
    ("SIDERÓPOLIS",FeedType.FECAM,"https://www.sideropolis.sc.gov.br/noticias/","governodesideropolis",0),
    ("SOMBRIO",FeedType.PROPRIO,"","",0),
    ("TIMBÉ DO SUL",FeedType.FECAM,"https://timbedosul.sc.gov.br/noticias/","prefeituratimbedosul",0),
    ("TREVISO",FeedType.IPM,"https://treviso.atende.net/cidadao/rss/noticias","prefeituradetreviso",1),
    ("TREZE DE MAIO",FeedType.FECAM,"https://www.trezedemaio.sc.gov.br/noticias/","prefeituradetrezedemaio",0),
    ("TUBARÃO",FeedType.FECAM,"https://tubarao.sc.gov.br/noticias/","prefeituradetubarao",0),
    ("TURVO",FeedType.FECAM,"https://turvo.sc.gov.br/noticias/","prefeituradeturvo.sc",0),
    ("URUSSANGA",FeedType.FECAM,"https://www.urussanga.sc.gov.br/noticias/","prefeituradeurussanga",0),
    ("BALNEÁRIO BARRA DO SUL",FeedType.IPM,"https://balneariobarradosul.atende.net/cidadao/rss/noticias","prefeituradebbs",1),
    ("ÁGUA DOCE",FeedType.FECAM,"https://aguadoce.sc.gov.br/noticias/","prefaguadoce.sc",0),
    ("ANITA GARIBALDI",FeedType.IPM,"https://anitagaribaldi.atende.net/cidadao/rss/noticias","prefeituradeanitagaribaldi",1),
    ("AGROLÂNDIA",FeedType.FECAM,"https://agrolandia.sc.gov.br/noticias/","prefeituradeagrolandia",0),
    ("ÁGUAS MORNAS",FeedType.FECAM,"https://aguasmornas.sc.gov.br/noticias/","prefeituraaguasmornas",0),
    ("ALFREDO WAGNER",FeedType.FECAM,"https://alfredowagner.sc.gov.br/noticias/","prefeituraalfredowagner",0),
    ("ANGELINA",FeedType.PROPRIO,"https://www.angelina.sc.gov.br/noticias.php","",0),
    ("ANITÁPOLIS",FeedType.FECAM,"https://anitapolis.sc.gov.br/noticias/","prefeituradeanitapolis",0),
    ("ANTÔNIO CARLOS",FeedType.FECAM,"https://antoniocarlos.sc.gov.br/noticias/","prefeituradeantoniocarlos",0),
    ("BIGUAÇU",FeedType.FECAM,"https://bigua.sc.gov.br/noticias/","prefeituradebiguacu",0),
    ("CANELINHA",FeedType.FECAM,"https://canelinha.sc.gov.br/noticias/","prefeituradecanelinha",0),
    ("FLORIANÓPOLIS",FeedType.PROPRIO,"https://www.pmf.sc.gov.br/noticias/index.php","",0),
    ("GOV. CELSO RAMOS",FeedType.FECAM,"https://celso.sc.gov.br/noticias/","prefeituragovernadorcelsoramos",0),
    ("LEOBERTO LEAL",FeedType.FECAM,"https://leobertoleal.sc.gov.br/noticias/","prefeituradeleobertoleal",0),
    ("MAJOR GERCINO",FeedType.FECAM,"https://majorgercino.sc.gov.br/noticias/","prefeiturademajorgercino",0),
    ("NOVA TRENTO",FeedType.FECAM,"https://novatrento.sc.gov.br/noticias/","prefeituranovatrento",0),
    ("PALHOÇA",FeedType.IPM,"https://palhoca.atende.net/cidadao/rss/noticias","prefeiturapalhoca",1),
    ("RANCHO QUEIMADO",FeedType.PROPRIO,"https://rq.sc.gov.br/noticias","",0),
    ("SANTO AMARO DA IMPERATRIZ",FeedType.PROPRIO,"","",0),
    ("SÃO BONIFÁCIO",FeedType.PROPRIO,"","",0),
    ("SÃO JOÃO BATISTA",FeedType.FECAM,"https://sjbatista.sc.gov.br/noticias/","prefeituradesjb",0),
    ("SÃO JOSÉ",FeedType.PROPRIO,"","",0),
    ("SÃO PEDRO DE ALCÂNTARA",FeedType.FECAM,"https://pmspa.sc.gov.br/noticias/","prefeiturasaopedrodealcantara",0),
    ("TIJUCAS",FeedType.PROPRIO,"","",0),
    ("ABDON BATISTA",FeedType.FECAM,"https://abdonbatista.sc.gov.br/noticias/","prefeituraabdon",0),
    ("ABELARDO LUZ",FeedType.FECAM,"https://abelardoluz.sc.gov.br/noticias/","prefeitura_abelardoluz",0),
    ("AGRONÔMICA",FeedType.FECAM,"https://agronomica.sc.gov.br/noticias/","agronomica.prefeitura",0),
    ("ÁGUAS DE CHAPECÓ",FeedType.FECAM,"https://aguasdechapeco.sc.gov.br/noticias/","aguas.dechapeco",0),
    ("ÁGUAS FRIAS",FeedType.FECAM,"https://aguasfrias.sc.gov.br/noticias/","prefeituradeaguasfrias",0),
    ("ALTO BELA VISTA",FeedType.IPM,"https://altobelavista.atende.net/cidadao/rss/noticias","prefeitura_abv",1),
    ("ANCHIETA",FeedType.FECAM,"https://www.anchieta.sc.gov.br/noticias/","municipiodeanchieta",0),
    ("APIÚNA",FeedType.FECAM,"https://www.apiuna.sc.gov.br/noticias/","pref.apiuna",0),
    ("ARABUTÃ",FeedType.IPM,"https://arabuta.atende.net/cidadao/rss/noticias","municipiodearabuta",1),
    ("ARAQUARI",FeedType.IPM,"https://araquari.atende.net/cidadao/rss/noticias","prefeitura_araquari",1),
    ("ARROIO TRINTA",FeedType.FECAM,"https://arroiotrinta.sc.gov.br/noticias/","arroiotrinta.sc",0),
    ("ARVOREDO",FeedType.IPM,"https://arvoredo.atende.net/cidadao/rss/noticias","prefeituraarvoredo",1),
    ("ASCURRA",FeedType.FECAM,"https://ascurra.sc.gov.br/noticias/","prefeituraascurra",0),
    ("ATALANTA",FeedType.FECAM,"https://atalanta.sc.gov.br/noticias/","prefeituradeatalanta",0),
    ("AURORA",FeedType.IPM,"https://aurora.atende.net/cidadao/rss/noticias","prefeituramunicipaldeaurorasc",1),
    ("BALNEÁRIO CAMBORIÚ",FeedType.PROPRIO,"","",0),
    ("BALNEÁRIO PIÇARRAS",FeedType.IPM,"https://balneariopicarras.atende.net/cidadao/rss/noticias","balpicarras",1),
    ("BANDEIRANTE",FeedType.FECAM,"https://bandeirante.sc.gov.br/noticias/","",0),
    ("BARRA BONITA",FeedType.FECAM,"https://barrabonita.sc.gov.br/noticias/","",0),
    ("BARRA VELHA",FeedType.IPM,"https://barravelha.atende.net/cidadao/rss/noticias","prefeituradebarravelha",1),
    ("BELA VISTA DO TOLDO",FeedType.FECAM,"https://www.pmbvt.sc.gov.br/noticias/","prefeiturabvtsc",0),
    ("BELMONTE",FeedType.FECAM,"https://belmonte.sc.gov.br/noticias/","prefeituradebelmonte",0),
    ("BENEDITO NOVO",FeedType.FECAM,"https://beneditonovo.sc.gov.br/noticias/","prefeiturabeneditonovo",0),
    ("BLUMENAU",FeedType.PROPRIO,"","",0),
    ("BOCAINA DO SUL",FeedType.FECAM,"https://bocaina.sc.gov.br/noticias/","prefbocainadosul",0),
    ("BOM JARDIM DA SERRA",FeedType.FECAM,"https://bomjardimdaserra.sc.gov.br/noticias/","prefeitura_bjs",0),
    ("BOM JESUS",FeedType.FECAM,"https://bomjesus.sc.gov.br/noticias/","prefeiturabomjesus_sc",0),
    ("BOM JESUS DO OESTE",FeedType.FECAM,"https://bomjesusdooeste.sc.gov.br/noticias/","municipiobomjesusdooeste",0),
    ("BOM RETIRO",FeedType.FECAM,"https://bomretiro.sc.gov.br/noticias/","prefeituradebomretiro",0),
    ("BOMBINHAS",FeedType.FECAM,"https://bombinhas.sc.gov.br/noticias/","prefeiturabombinhas",0),
    ("BOTUVERÁ",FeedType.PROPRIO,"","",0),
    ("BRAÇO DO TROMBUDO",FeedType.FECAM,"https://bracodotrombudo.sc.gov.br/noticias/","prefeituramunicipalbraco",0),
    ("BRUNÓPOLIS",FeedType.FECAM,"https://brunopolis.sc.gov.br/noticias/","",0),
    ("BRUSQUE",FeedType.PROPRIO,"","",0),
    ("CAÇADOR",FeedType.FECAM,"https://cacador.sc.gov.br/category/cacador/","prefeituradecacador",0),
    ("CAIBI",FeedType.FECAM,"https://caibi.sc.gov.br/noticias/","prefeituracaibi",0),
    ("CALMON",FeedType.FECAM,"https://calmon.sc.gov.br/noticias/","prefeituradecalmon",0),
    ("CAMBORIÚ",FeedType.PROPRIO,"","",0),
    ("CAMPO ALEGRE",FeedType.FECAM,"https://campoalegre.sc.gov.br/noticias/","prefeituradecampoalegre",0),
    ("CAMPO BELO DO SUL",FeedType.FECAM,"https://campobelodosul.sc.gov.br/noticias/","prefcampobelodosul",0),
    ("CAMPO ERÊ",FeedType.PROPRIO,"https://campoere.sc.gov.br/noticias/","municipiodecampoere",0),
    ("CAMPOS NOVOS",FeedType.FECAM,"https://camposnovos.sc.gov.br/noticias/","prefeituracn",0),
    ("CANOINHAS",FeedType.IPM,"https://canoinhas.atende.net/cidadao/rss/noticias","prefeituracanoinhas_oficial",1),
    ("CAPÃO ALTO",FeedType.FECAM,"https://capaoalto.sc.gov.br/noticias/","prefeituradecapaoalto",0),
    ("CAPINZAL",FeedType.FECAM,"https://capinzal.sc.gov.br/noticias/","prefeituradecapinzal",0),
    ("CATANDUVAS",FeedType.FECAM,"https://catanduvas.sc.gov.br/noticias/","prefeituradecatanduvas",0),
    ("CAXAMBU DO SUL",FeedType.IPM,"https://caxambudosul.atende.net/cidadao/rss/noticias","caxambu_do_sul",1),
    ("CELSO RAMOS",FeedType.FECAM,"https://celsoramos.sc.gov.br/noticias/","prefeituradecelsoramos",0),
    ("CERRO NEGRO",FeedType.FECAM,"https://cerronegro.sc.gov.br/noticias/","prefeituracerronegrooficial",0),
    ("CHAPADÃO DO LAGEADO",FeedType.IPM,"https://chapadaodolageado.atende.net/cidadao/rss/noticias","chapadaodolageado_oficiial",1),
    ("CHAPECÓ",FeedType.PROPRIO,"","",0),
    ("CONCÓRDIA",FeedType.IPM,"https://concordia.atende.net/cidadao/rss/noticias","prefeitura_concordia",1),
    ("CORDILHEIRA ALTA",FeedType.FECAM,"https://pmcordi.sc.gov.br/noticias/","cordilheiraalta",0),
    ("CORONEL FREITAS",FeedType.FECAM,"https://coronelfreitas.sc.gov.br/category/sem-categoria/","prefeituradecoronelfreitas",0),
    ("CORONEL MARTINS",FeedType.FECAM,"https://coronelmartins.sc.gov.br/noticias/","prefa_coronelmartins",0),
    ("CORREIA PINTO",FeedType.FECAM,"https://correiapinto.sc.gov.br/category/sem-categoria/","pcorreiapinto",0),
    ("CORUPÁ",FeedType.IPM,"https://corupa.atende.net/cidadao/rss/noticias","prefeituradecorupa",1),
    ("CUNHA PORÃ",FeedType.IPM,"https://cunhapora.atende.net/cidadao/rss/noticias","municipiocunhapora",1),
    ("CUNHATAÍ",FeedType.FECAM,"https://cunhatai.sc.gov.br/noticias/","prefeituradecunhatai",0),
    ("CURITIBANOS",FeedType.FECAM,"https://curitibanos.sc.gov.br/noticias/","prefeituradecuritibanos",0),
    ("DESCANSO",FeedType.FECAM,"https://descanso.sc.gov.br/noticias/","descansosc_",0),
    ("DIONÍSIO CERQUEIRA",FeedType.FECAM,"https://dionisiocerqueira.sc.gov.br/noticias/","prefeituradionisiocerqueira",0),
    ("DONA EMMA",FeedType.FECAM,"https://donaemma.sc.gov.br/noticias/","prefeitura_donaemma",0),
    ("DOUTOR PEDRINHO",FeedType.FECAM,"https://doutorpedrinho.sc.gov.br/noticias/","prefeituradoutorpedrinho",0),
    ("ENTRE RIOS",FeedType.FECAM,"https://entrerios.sc.gov.br/noticias/","assecom_entrerios",0),
    ("ERVAL VELHO",FeedType.FECAM,"https://ervalvelho.sc.gov.br/noticias/","prefeituradeervalvelho",0),
    ("FAXINAL DOS GUEDES",FeedType.FECAM,"https://faxinal.sc.gov.br/noticias/","prefeiturafaxinaldosguedes",0),
    ("FLOR DO SERTÃO",FeedType.FECAM,"https://www.flordosertao.sc.gov.br/noticias/","flordosertaosc",0),
    ("FORMOSA DO SUL",FeedType.FECAM,"https://formosa.sc.gov.br/noticias/","formosadosuloficial",0),
    ("FRAIBURGO",FeedType.IPM,"https://fraiburgo.atende.net/cidadao/rss/noticias","prefeituradefraiburgo",1),
    ("FREI ROGÉRIO",FeedType.FECAM,"https://freirogerio.sc.gov.br/noticias/","prefeitura_frei",0),
    ("GALVÃO",FeedType.FECAM,"https://www.galvao.sc.gov.br/noticias/","galvaosc",0),
    ("GARUVA",FeedType.IPM,"https://garuva.atende.net/cidadao/rss/noticias","prefeituradegaruva",1),
    ("GASPAR",FeedType.FECAM,"https://www.gaspar.sc.gov.br/noticias/","prefeituradegaspar",0),
    ("GUABIRUBA",FeedType.PROPRIO,"https://guabiruba.sc.gov.br/noticias/","prefeituradeguabiruba",0),
    ("GUARACIABA",FeedType.IPM,"https://guaraciaba.atende.net/cidadao/rss/noticias","prefe_guaraciaba",1),
    ("GUARAMIRIM",FeedType.IPM,"https://guaramirim.atende.net/cidadao/rss/noticias","prefeituradeguaramirim",1),
    ("GUARUJÁ DO SUL",FeedType.IPM,"https://guarujadosul.atende.net/cidadao/rss/noticias","guarujadosul",1),
    ("GUATAMBU",FeedType.FECAM,"https://guatambu.sc.gov.br/noticias/","municipiodeguatambu",0),
    ("HERVAL D´OESTE",FeedType.FECAM,"https://hervaldoeste.sc.gov.br/noticias/","prefeituradehervaldoeste",0),
    ("IBIAM",FeedType.FECAM,"https://ibiam.sc.gov.br/noticias/","prefeituradeibiam",0),
    ("IBICARÉ",FeedType.FECAM,"https://ibicare.sc.gov.br/noticias/","",0),
    ("IBIRAMA",FeedType.PROPRIO,"","",0),
    ("ILHOTA",FeedType.FECAM,"https://ilhota.sc.gov.br/noticias/","prefeiturailhota",0),
    ("IMBUIA",FeedType.FECAM,"https://imbuia.sc.gov.br/noticias/","prefeituradeimbuia",0),
    ("INDAIAL",FeedType.IPM,"https://indaial.atende.net/cidadao/rss/noticias","prefeituradeindaial",1),
    ("IOMERÊ",FeedType.FECAM,"https://iomere.sc.gov.br/noticias/","prefeituraiomere",0),
    ("IPIRA",FeedType.FECAM,"https://ipira.sc.gov.br/noticias/","prefipira",0),
    ("IPORÃ DO OESTE",FeedType.IPM,"https://iporadooeste.atende.net/cidadao/rss/noticias","prefeitura.iporadooeste",1),
    ("IPUAÇU",FeedType.FECAM,"https://ipuacu.sc.gov.br/noticias/","ipuacuprefeitura",0),
    ("IPUMIRIM",FeedType.FECAM,"https://ipumirim.sc.gov.br/noticias/","prefeituradeipumirim",0),
    ("IRACEMINHA",FeedType.FECAM,"https://iraceminha.sc.gov.br/noticias/","prefeituradeiraceminha",0),
    ("IRANI",FeedType.FECAM,"https://irani.sc.gov.br/noticias/","prefeitura.deirani",0),
    ("IRATI",FeedType.FECAM,"https://irati.sc.gov.br/noticias/","",0),
    ("IRINEÓPOLIS",FeedType.IPM,"https://irineopolis.atende.net/cidadao/rss/noticias","prefeituradeirineopolis",1),
    ("ITÁ",FeedType.IPM,"https://ita.atende.net/cidadao/rss/noticias","prefeituradeita",1),
    ("ITAIÓPOLIS",FeedType.FECAM,"https://itaiopolis.sc.gov.br/noticias/","",0),
    ("ITAJAÍ",FeedType.PROPRIO,"","",0),
    ("ITAPEMA",FeedType.PROPRIO,"","",0),
    ("ITAPIRANGA",FeedType.IPM,"https://itapiranga.atende.net/cidadao/rss/noticias","municipiodeitapiranga",1),
    ("ITAPOÁ",FeedType.IPM,"https://itapoa.atende.net/cidadao/rss/noticias","prefeitura_itapoa",1),
    ("ITUPORANGA",FeedType.PROPRIO,"","",0),
    ("JABORÁ",FeedType.FECAM,"https://jabora.sc.gov.br/noticias/","municipiodejabora",0),
    ("JARAGUÁ DO SUL",FeedType.PROPRIO,"","",0),
    ("JARDINÓPOLIS",FeedType.FECAM,"https://jardinopolis.sc.gov.br/noticias/","",0),
    ("JOAÇABA",FeedType.FECAM,"https://joacaba.sc.gov.br/noticias/","prefeituradejoacaba",0),
    ("JOINVILLE",FeedType.PROPRIO,"","",0),
    ("JOSÉ BOITEUX",FeedType.FECAM,"https://www.pmjb.sc.gov.br/noticias/","prefeiturajoseboiteux",0),
    ("JUPIÁ",FeedType.FECAM,"https://jupia.sc.gov.br/noticias/","",0),
    ("LACERDÓPOLIS",FeedType.FECAM,"https://www.lacerdopolis.sc.gov.br/noticias/","municipiodelacerdopolis",0),
    ("LAGES",FeedType.PROPRIO,"","",0),
    ("LAJEADO GRANDE",FeedType.FECAM,"https://lajeadogrande.sc.gov.br/noticias/","prefeituradelajeadogrande",0),
    ("LAURENTINO",FeedType.FECAM,"https://laurentino.sc.gov.br/noticias/","laurentinosc",0),
    ("LEBON RÉGIS",FeedType.FECAM,"https://lebonregis.sc.gov.br/noticias/","pref.lebon",0),
    ("LINDÓIA DO SUL",FeedType.FECAM,"https://lindoiadosul.sc.gov.br/category/noticias/","prefeituradelindoiadosul",0),
    ("LONTRAS",FeedType.IPM,"https://lontras.atende.net/cidadao/rss/noticias","prefeituradelontras",1),
    ("LUIZ ALVES",FeedType.IPM,"https://luizalves.atende.net/cidadao/rss/noticias","prefeituraluizalves",1),
    ("LUZERNA",FeedType.FECAM,"https://luzerna.sc.gov.br/noticias/","municipiodeluzerna",0),
    ("MACIEIRA",FeedType.FECAM,"https://macieira.sc.gov.br/noticias/","",0),
    ("MAFRA",FeedType.FECAM,"https://mafra.sc.gov.br/category/noticias/","prefeiturademafra",0),
    ("MAJOR VIEIRA",FeedType.FECAM,"https://majorvieira.sc.gov.br/noticias/","prefeituramajorvieira",0),
    ("MARAVILHA",FeedType.FECAM,"https://maravilha.sc.gov.br/noticias/","prefeituramaravilha",0),
    ("MAREMA",FeedType.FECAM,"https://marema.sc.gov.br/noticias/","prefeiturademarema",0),
    ("MASSARANDUBA",FeedType.IPM,"https://massaranduba.atende.net/cidadao/rss/noticias","massarandubasc",1),
    ("MATOS COSTA",FeedType.FECAM,"https://matoscosta.sc.gov.br/noticias/","prefeitura_de_matoscosta",0),
    ("MIRIM DOCE",FeedType.FECAM,"https://mirimdoce.sc.gov.br/noticias/","prefeituramirimdoce",0),
    ("MODELO",FeedType.IPM,"https://modelo.atende.net/cidadao/rss/noticias","municipiodemodelooficial",1),
    ("MONDAÍ",FeedType.FECAM,"https://mondai.sc.gov.br/noticias/","prefeituramondai",0),
    ("MONTE CARLO",FeedType.FECAM,"https://www.montecarlo.sc.gov.br/noticias/","prefeiturademontecarlo",0),
    ("MONTE CASTELO",FeedType.FECAM,"https://montecastelo.sc.gov.br/noticias/","prefeiturademontecastelo",0),
    ("NAVEGANTES",FeedType.PROPRIO,"","",0),
    ("NOVA ERECHIM",FeedType.IPM,"https://novaerechim.atende.net/cidadao/rss/noticias","municipiodenovaerechim",1),
    ("NOVA ITABERABA",FeedType.IPM,"https://novaitaberaba.atende.net/cidadao/rss/noticias","novaitaberabaprefeitura",1),
    ("NOVO HORIZONTE",FeedType.FECAM,"https://novohorizonte.sc.gov.br/noticias/","",0),
    ("OTACÍLIO COSTA",FeedType.FECAM,"https://otaciliocosta.sc.gov.br/noticias/","prefeituradeotaciliocosta",0),
    ("OURO",FeedType.FECAM,"https://ouro.sc.gov.br/noticias/","prefeituradeouro",0),
    ("OURO VERDE",FeedType.FECAM,"https://ouroverde.sc.gov.br/noticias/","ouroverdeprefeitura",0),
    ("PAIAL",FeedType.IPM,"https://paial.atende.net/cidadao/rss/noticias","prefeituradepaial",1),
    ("PAINEL",FeedType.FECAM,"https://painel.sc.gov.br/noticias/","prefeiturapaineloficial",0),
    ("PALMA SOLA",FeedType.IPM,"https://palmasola.atende.net/cidadao/rss/noticias","prefeiturapalmasola",1),
    ("PALMEIRA",FeedType.FECAM,"https://palmeira.sc.gov.br/category/noticias/","palmeirascoficial",0),
    ("PALMITOS",FeedType.FECAM,"https://palmitos.sc.gov.br/noticias/","prefpalmitos",0),
    ("PAPANDUVA",FeedType.FECAM,"https://papanduva.sc.gov.br/noticias/","prefeiturapapanduva",0),
    ("PARAÍSO",FeedType.IPM,"https://paraiso.atende.net/cidadao/rss/noticias","",1),
    ("PASSOS MAIA",FeedType.FECAM,"https://passosmaia.sc.gov.br/noticias/","prefeiturapassosmaia",0),
    ("PENHA",FeedType.IPM,"https://penha.atende.net/cidadao/rss/noticias","prefeiturapenha",1),
    ("PERITIBA",FeedType.FECAM,"https://peritiba.sc.gov.br/noticias/","prefeituraperitiba",0),
    ("PETROLÂNDIA",FeedType.FECAM,"https://petrolandia.sc.gov.br/noticias/","prefeiturapetrolandiasc",0),
    ("PINHALZINHO",FeedType.IPM,"https://pinhalzinho.atende.net/cidadao/rss/noticias","prefeituradepinhalzinho",1),
    ("PINHEIRO PRETO",FeedType.FECAM,"https://pinheiropreto.sc.gov.br/noticias/","prefeiturapinheiropreto",0),
    ("PIRATUBA",FeedType.FECAM,"https://piratuba.sc.gov.br/noticias/","prefeituradepiratuba",0),
    ("PLANALTO ALEGRE",FeedType.IPM,"https://planaltoalegre.atende.net/cidadao/rss/noticias","prefeituradeplanaltoalegre",1),
    ("POMERODE",FeedType.PROPRIO,"","",0),
    ("PONTE ALTA",FeedType.FECAM,"https://pontealta.sc.gov.br/noticias/","prefeituradepontealta",0),
    ("PONTE ALTA DO NORTE",FeedType.FECAM,"https://pmpan.sc.gov.br/noticias/","prefeituradepan",0),
    ("PONTE SERRADA",FeedType.FECAM,"https://ponteserrada.sc.gov.br/noticias/","ponte_serrada_oficial",0),
    ("PORTO BELO",FeedType.FECAM,"https://portobelo.sc.gov.br/noticias/","",0),
    ("PORTO UNIÃO",FeedType.FECAM,"https://www.portouniao.sc.gov.br/noticias/","prefsportouniao",0),
    ("POUSO REDONDO",FeedType.FECAM,"https://pousoredondo.sc.gov.br/noticias/","prefeituradepousoredondo",0),
    ("PRESIDENTE CASTELO BRANCO",FeedType.FECAM,"https://castellobranco.sc.gov.br/noticias/","",0),
    ("PRESIDENTE GETÚLIO",FeedType.IPM,"https://presidentegetulio.atende.net/cidadao/rss/noticias","prefeiturapresidentegetulio",1),
    ("PRESIDENTE NEREU",FeedType.IPM,"https://presidentenereu.atende.net/cidadao/rss/noticias","municipiopresidentenereu",1),
    ("PRINCESA",FeedType.IPM,"https://princesa.atende.net/cidadao/rss/noticias","",1),
    ("QUILOMBO",FeedType.FECAM,"https://quilombo.sc.gov.br/noticias/","municipiodequilombo",0),
    ("RIO DAS ANTAS",FeedType.FECAM,"https://riodasantas.sc.gov.br/noticias/","prefeiturariodasantas",0),
    ("RIO DO CAMPO",FeedType.IPM,"https://riodocampo.atende.net/cidadao/rss/noticias","prefeituraderiodocampo",1),
    ("RIO DO OESTE",FeedType.FECAM,"https://riodooeste.sc.gov.br/noticias/","prefeituraderiodooeste",0),
    ("RIO DO SUL",FeedType.IPM,"https://riodosul.atende.net/cidadao/rss/noticias","prefeiturariodosul",1),
    ("RIO DOS CEDROS",FeedType.FECAM,"https://riodoscedros.sc.gov.br/noticias/","prefeiturariodoscedros",0),
    ("RIO NEGRINHO",FeedType.PROPRIO,"","",0),
    ("RIO RUFINO",FeedType.FECAM,"https://riorufino.sc.gov.br/noticias/","prefeitura_rio_rufino",0),
    ("RIQUEZA",FeedType.IPM,"https://riqueza.atende.net/cidadao/rss/noticias","prefeituraderiqueza",1),
    ("RODEIO",FeedType.FECAM,"https://rodeio.sc.gov.br/category/noticias/","prefeituraderodeio",0),
    ("ROMELÂNDIA",FeedType.FECAM,"https://romelandia.sc.gov.br/noticias/","municipioderomelandia",0),
    ("SALETE",FeedType.FECAM,"https://salete.sc.gov.br/noticias/","prefeituradesalete",0),
    ("SALTINHO",FeedType.FECAM,"https://saltinho.sc.gov.br/noticias/","municipio.saltinho",0),
    ("SALTO VELOSO",FeedType.FECAM,"https://saltoveloso.sc.gov.br/noticias/","prefeiturasaltoveloso",0),
    ("SANTA CECÍLIA",FeedType.FECAM,"https://santacecilia.sc.gov.br/noticias/","prefsantacecilia",0),
    ("SANTA HELENA",FeedType.IPM,"https://santahelenasc.atende.net/cidadao/rss/noticias","santahelenasc",1),
    ("SANTA TEREZINHA",FeedType.FECAM,"https://santaterezinha.sc.gov.br/noticias/","pmstaterezinha",0),
    ("SANTA TEREZINHA DO PROGRESSO",FeedType.FECAM,"https://staterezinhaprogresso.sc.gov.br/noticias/","",0),
    ("SANTIAGO DO SUL",FeedType.FECAM,"https://santiagodosul.sc.gov.br/noticias/","municipiodesantiagodosul",0),
    ("SÃO BENTO DO SUL",FeedType.IPM,"https://saobentodosul.atende.net/cidadao/rss/noticias","pref.saobento",1),
    ("SÃO BERNARDINO",FeedType.FECAM,"https://saobernardino.sc.gov.br/noticias/","",0),
    ("SÃO CARLOS",FeedType.IPM,"https://saocarlos.atende.net/cidadao/rss/noticias","saocarlos.sc",1),
    ("SÃO CRISTÓVÃO DO SUL",FeedType.FECAM,"https://pmsc.sc.gov.br/noticias/","pref.saocristovaodosul",0),
    ("SÃO DOMINGOS",FeedType.FECAM,"https://saodomingos.sc.gov.br/noticias/","prefeituradesaodomingos2023",0),
    ("SÃO FRANCISCO DO SUL",FeedType.PROPRIO,"","",0),
    ("SÃO JOÃO DO ITAPERIÚ",FeedType.IPM,"https://saojoaodoitaperiu.atende.net/cidadao/rss/noticias","",1),
    ("SÃO JOÃO DO OESTE",FeedType.FECAM,"https://saojoao.sc.gov.br/noticias/","saojoaosc",0),
    ("SÃO JOAQUIM",FeedType.FECAM,"https://www.saojoaquim.sc.gov.br/noticias/","prefeiturasj",0),
    ("SÃO JOSÉ DO CEDRO",FeedType.IPM,"https://saojosedocedro.atende.net/cidadao/rss/noticias","pref_cedro",1),
    ("SÃO JOSÉ DO CERRITO",FeedType.FECAM,"https://www.cerrito.sc.gov.br/noticias/","prefeitura.sjc",0),
    ("SÃO LOURENÇO DO OESTE",FeedType.PROPRIO,"","",0),
    ("SÃO MIGUEL DA BOA VISTA",FeedType.FECAM,"https://saomigueldaboavista.sc.gov.br/noticias/","municipiodesaomigueldaboavista",0),
    ("SÃO MIGUEL DO OESTE",FeedType.PROPRIO,"","",0),
    ("SAUDADES",FeedType.FECAM,"https://saudades.sc.gov.br/noticias/","municipio.saudadessc",0),
    ("SCHROEDER",FeedType.FECAM,"https://schroeder.sc.gov.br/noticias/","prefeituradeschroeder",0),
    ("SEARA",FeedType.IPM,"https://seara.atende.net/cidadao/rss/noticias","prefeituraseara",1),
    ("SERRA ALTA",FeedType.IPM,"https://serraalta.atende.net/cidadao/rss/noticias","municipiodeserraalta",1),
    ("SUL BRASIL",FeedType.FECAM,"https://sulbrasil.sc.gov.br/noticias/","prefeituradesulbrasil",0),
    ("TAIÓ",FeedType.FECAM,"https://taio.sc.gov.br/noticias/","prefeituradetaio",0),
    ("TANGARÁ",FeedType.PROPRIO,"","",0),
    ("TIGRINHOS",FeedType.FECAM,"https://www.tigrinhos.sc.gov.br/noticias/","municipiodetigrinhos",0),
    ("TIMBÓ",FeedType.PROPRIO,"","",0),
    ("TIMBÓ GRANDE",FeedType.FECAM,"https://timbogrande.sc.gov.br/noticias/","prefeituradetimbogrande",0),
    ("TRÊS BARRAS",FeedType.PROPRIO,"","",0),
    ("TREZE TÍLIAS",FeedType.IPM,"https://trezetilias.atende.net/cidadao/rss/noticias","prefeituradetrezetilias",1),
    ("TROMBUDO CENTRAL",FeedType.FECAM,"https://www.trombudocentral.sc.gov.br/noticias/","prefeituradetrombudo",0),
    ("TUNÁPOLIS",FeedType.FECAM,"https://tunapolis.sc.gov.br/noticias/","municipiodetunapolis",0),
    ("UNIÃO DO OESTE",FeedType.FECAM,"https://uniaodooeste.sc.gov.br/noticias/","uniao.do.oeste",0),
    ("URUBICI",FeedType.PROPRIO,"","",0),
    ("URUPEMA",FeedType.FECAM,"https://www.urupema.sc.gov.br/noticias/","prefeituradeurupema",0),
    ("VARGEÃO",FeedType.FECAM,"https://vargeao.sc.gov.br/noticias/","prefeituravargeao",0),
    ("VARGEM",FeedType.FECAM,"https://www.vargem.sc.gov.br/noticias/","prefeituravargemsc",0),
    ("VARGEM BONITA",FeedType.FECAM,"https://vargembonita.sc.gov.br/noticias/","prefeituradevargembonita",0),
    ("VIDAL RAMOS",FeedType.PROPRIO,"","",0),
    ("VIDEIRA",FeedType.IPM,"https://videira.atende.net/cidadao/rss/noticias","prefeituradevideira",1),
    ("VÍTOR MEIRELES",FeedType.FECAM,"https://vitormeireles.sc.gov.br/noticias/","",0),
    ("WITMARSUM",FeedType.FECAM,"https://witmarsum.sc.gov.br/noticias/","",0),
    ("XANXERÊ",FeedType.FECAM,"https://xanxere.sc.gov.br/noticias/","prefeitura_de_xanxere",0),
    ("XAVANTINA",FeedType.FECAM,"https://xavantina.sc.gov.br/noticias/","prefeituradexavantina",0),
    ("XAXIM",FeedType.FECAM,"https://www.xaxim.sc.gov.br/noticias/","prefeituradexaxim",0),
    ("ZORTÉA",FeedType.IPM,"https://zortea.atende.net/cidadao/rss/noticias","prefeiturazortea",1)
]

"""
SAMPLE_TITLES = [
    "Prefeitura entrega nova unidade de saúde no bairro",
    "Município recebe prêmio estadual de gestão pública",
    "Programa de reciclagem amplia coleta seletiva na cidade",
    "Nova ciclovia é inaugurada na região central",
    "Cidade lança edital de incentivo a pequenos negócios",
    "Escola municipal é destaque nacional em avaliação de ensino",
    "Prefeitura anuncia investimento em pavimentação de ruas",
    "Feira de agricultura familiar movimenta economia local",
]
"""

def run() -> None:
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        if db.query(City).count() > 0:
            print("Banco já possui dados. Nada a fazer.")
            return

        cities = []
        for name, url_type, url_path, instagram, active in CITIES:
            city = City(
                name=name,
                url_type=url_type,
                url_path=url_path,
                instagram=instagram,
                active=active,
            )
            db.add(city)
            cities.append(city)
        db.flush()

        """
        now = datetime.utcnow()
        for i, city in enumerate(cities):
            for j, title in enumerate(SAMPLE_TITLES):
                db.add(
                    News(
                        city_id=city.id,
                        title=f"{title} de {city.name}",
                        date=now - timedelta(hours=i + j),
                        news_url=f"https://exemplo.gov.br/noticia/{i}-{j}",
                        description=(
                            "Notícia de exemplo gerada para fins de demonstração "
                            "e testes locais do Prefa.News."
                        ),
                        active=True,
                        value=100 - (i + j),
                    )
                )
        """
        db.commit()
        print(f"Seed concluído: {len(cities)} cidades.")
    finally:
        db.close()


if __name__ == "__main__":
    run()
